### ISSUE TITLE
Error: Module version mismatch. Expected 46, got 57.

### ISSUE THREAD

**Issue by z3rone** [TimSamshuijzen/iotaproxy#14]
running the index.js throws this error:
/var/nodejs/iotaproxy/node_modules/bindings/bindings.js:83
        throw e
        ^
Error: Module version mismatch. Expected 46, got 57.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/var/nodejs/iotaproxy/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/var/nodejs/iotaproxy/node_modules/ref/lib/ref.js:5:47)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Deleting `node_modules/` and running `npm install` again does not help.

**Comment by chadfurman** [comment]
Are you sure you're on the latest version?  What version of nodejs are you running?  Make sure you're on the latest LTS version of NodeJS, or atleast A long-term support version.

**Comment by z3rone** [comment]
I solved the problem, but it might not be 100% repeatable.

1. I reinstalled Debian on my server and still got some errors while installing the dependencies (during installation of ffi)
2. I downgraded to nodejs 7.x

Now it works!

It's no wonder because fii seems generally fails to compile with node >7.x (https://travis-ci.org/node-ffi/node-ffi)
