### ISSUE TITLE
Starting of Proxy server doesn't work

### ISSUE THREAD

**Issue by primius** [TimSamshuijzen/iotaproxy#16]
When trying to start the proxy server with:
            **node --harmony index.js**
im getting the following error message:

**module.js:540
    throw err;
    ^
Error: Cannot find module 'ffi'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Eclipse-Workspace\iotaproxy\lib\ccurlprovider.js:11:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)**

**Comment by primius** [comment]
It seems you have to install a module called 'ffi' in addition. It can be done with the following command:
**npm install ffi**

**Comment by nicoschtein** [comment]
`ffi` is a dependency, which is included in [package.json](https://github.com/TimSamshuijzen/iotaproxy/blob/master/package.json)
[Instructions on REAMDE.md](https://github.com/TimSamshuijzen/iotaproxy#instructions) include a step `npm install` which should install all dependencies, in this case `ffi`.
