### ISSUE TITLE
Doesn't work at all really

### ISSUE THREAD

**Issue by intermension** [TimSamshuijzen/iotaproxy#2]
Crashes with every request.

ReferenceError: requestbodyOb is not defined
    at IncomingMessage.<anonymous> (D:\iotaproxy\node_modules\iotaproxy\lib\iotaproxy.js:64:27)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by TimSamshuijzen** [comment]
Caused by a missing let keyword. Is fixed and should be working now (thanks to capaj).
