### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by magussiro** [TimSamshuijzen/iotaproxy#7]
I'm using Mac to install iotaproxy, but something goes wrong

 ref@1.3.5 install /Users/Magus 1/Project/BlockChain/iotaproxy/node_modules/ref
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
clang: error: no such file or directory: '1/.node-gyp/6.11.3/include/node'
clang: error: no such file or directory: '1/.node-gyp/6.11.3/src'
clang: error: no such file or directory: '1/.node-gyp/6.11.3/deps/uv/include'
clang: error: no such file or directory: '1/.node-gyp/6.11.3/deps/v8/include'
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Magus 1/Project/BlockChain/iotaproxy/node_modules/ref
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN iotaproxy@1.0.0 No repository field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ref
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Magus 1/Project/BlockChain/iotaproxy/npm-debug.log
[npm-debug.txt](https://github.com/TimSamshuijzen/iotaproxy/files/1295594/npm-debug.txt)

**Comment by TimSamshuijzen** [comment]
Hi @magussiro, I haven't been able to test it on a Mac. Anyone else having this problem? Any solutions or suggestions?

**Comment by MichaelBakunin** [comment]
I was having this problem on Ubuntu 16.04. The install seems to work if you downgrade/upgrade to Node 8.x and do an npm install.

I'm still having problems getting iotaproxy working with iota-commandline-wallet though.

**Comment by chadfurman** [comment]
make sure you're running a LTS version of node -- what version were you running?

**Comment by MichaelBakunin** [comment]
Thanks for taking time to reply. It's v8.9.1. Iotaproxy seems to be running fine and comes back with a healthy looking

IOTA proxy server started
POW timeout is set to 15 min
Listening on port 14265
Relaying requests to https://potato.iotasalad.org:80

I have set 'provider': 'http://localhost:14265', in my iota-wallet-config.js

but if I try to GetConfirmationState or Replay I get this error 

{ status: "error", message: "Invalid Response: Not Found"} which is rather vauge.

**Comment by anistark** [comment]
This still exists.
`node-gyp configure` fails with `gyp: binding.gyp not found` configuration error.

Any resolution for mac ?

**Comment by nicoschtein** [comment]
@anistark what version of node are you using ?

**Comment by anistark** [comment]
@nicoschtein v9.5.0

**Comment by nicoschtein** [comment]
@anistark try node LTS (8.x), that one seems to work fine with current iotaproxy code

**Comment by ckrmml** [comment]
@anistark v8.9.1 lts works, `ffi` in `ccurlprovider.js` won't work with higher ones

**Comment by anistark** [comment]
Alright it worked with v8.9.4  👍 
Thanks @nicoschtein and @ckrmml
